config/routes.rb
Rails.application.routes.draw do
  get '/results' => 'results#show'

  root to: 'static_pages#top'
  get '/privacy', to: 'static_pages#privacy'
  get '/terms', to: 'static_pages#terms'

  get '*path', to: 'application#render_404'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower_saying.rb
class FollowerSaying < ApplicationRecord
  belongs_to :kojirase_result
end

app/models/kojirase_result.rb
class KojiraseResult < ApplicationRecord
  has_many :follower_sayings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #herokuapp.comから独自ドメインへリダイレクト
  before_action :ensure_domain
  FQDN = 'kojirase-shindan.com'

  # redirect correct server from herokuapp domain for SEO
  def ensure_domain
    return unless /\.herokuapp.com/ =~ request.host

  # 主にlocalテスト用の対策80と443以外でアクセスされた場合ポート番号をURLに含める
    port = ":#{request.port}" unless [80, 443].include?(request.port)
    redirect_to "#{request.protocol}#{FQDN}#{port}#{request.path}", status: :moved_permanently
  end

  add_flash_types :success, :info, :warning, :danger

  rescue_from Exception, with: :render_500
  rescue_from ActionController::RoutingError, with: :render_404

  rescue_from Twitter::Error::Unauthorized, with: :unauthorized
  rescue_from Twitter::Error::NotFound, with: :not_found
  rescue_from Twitter::Error::TooManyRequests, with: :too_many_requests

  def render_500
    render file: "#{Rails.root}/public/500.html", layout: false, status: 505
  end

  # 存在しないページへのアクセス時でのエラー
  def render_404
    render file: "#{Rails.root}/public/404.html", layout: false, status: 404
  end

  def unauthorized
    flash.now[:danger] = '非公開アカウントです。公開アカウントを入力してください。'
    render 'static_pages/top'
  end

  def not_found
    flash.now[:danger] = '有効なアカウントを入力してください。'
    render 'static_pages/top'
  end

  def too_many_requests
    flash.now[:danger] = "リクエストが集中しています\n最大15分待ってから再度試して下さい。"
    render 'static_pages/top'
  end

  # 環境変数の設定
  Dotenv.load
  HOSTNAME = ENV['HOSTNAME']
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  GOOGLE_API_KEY = ENV['GOOGLE_API_KEY']

  def show
    # 送られてきたIDからユーザーを取得
    @user = twitter_client.user(params[:user])

    # ユーザーのタイムライン200件取得
    tweets = twitter_client.user_timeline(params[:user], count: 200, tweet_mode: 'extended')

    # グラフに使うポイント取得
    @follower_point = FollowerAnalysisService.new(params[:user], twitter_client).call
    @spec_point = SpecAnalysisService.new(params[:user], twitter_client, tweets).call
    @desperate_point = DesperateAnalysisService.new(params[:user], twitter_client, tweets).call
    @apo_point = ApoAnalysisService.new(params[:user], twitter_client, tweets).call
    @numa_point = NumaAnalysisService.new(params[:user], twitter_client, tweets).call

    # こじらせレベル(1~5段階)を取得
    @kojirase_level = ResultService.new(@spec_point, @apo_point, @numa_point,
                                        @desperate_point).kojirase_level

    # こじらせレベルに応じた結果をデータベースから探す
    @kojirase_result = KojiraseResult.find_by(level: @kojirase_level)
    @follower_saying = @kojirase_result.follower_sayings.find_by(follower_point: @follower_point)

    # youtube
    @cat_youtube_data = find_videos('猫 癒し')
  end

  private

  def twitter_client
    @twitter_client ||= Twitter::REST::Client.new do |config|
      config.consumer_key = ENV['CONSUMER_KEY']
      config.consumer_secret = ENV['CONSUMER_SECRET']
      config.access_token = ENV['ACCESS_TOKEN']
      config.access_token_secret = ENV['ACCESS_SECRET']
    end
  end

  def find_videos(keyword, after: 1.months.ago, before: Time.now)
    service = Google::Apis::YoutubeV3::YouTubeService.new
    service.key = GOOGLE_API_KEY

    next_page_token = nil
    opt = {
      q: keyword,
      type: 'video',
      max_results: 3,
      order: :date,
      page_token: next_page_token,
      published_after: after.iso8601,
      published_before: before.iso8601
    }
    service.list_searches(:snippet, opt)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top; end

  def privacy; end

  def terms; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = '')
    base_title = ' -こじらせ診断- '
    title.empty? ? base_title : title + base_title
  end

  def default_meta_tags
    {
      site: 'こじらせ診断',
      title: 'そこのあなた、こじらせてない？',
      reverse: true,
      charset: 'utf-8',
      description: 'ツイートからこじらせ度を診断するアプリ',
      keywords: 'こじらせ, 診断, メンヘラ, 女性, 婚活',
      canonical: request.original_url,
      separator: '|',
      icon: [
        { href: image_url('top-girl.png') },
        { href: image_url('top-girl.png'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/jpg' }
      ],
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: request.original_url,
        image: image_url('ogp.png'),
        locale: 'ja_JP'
      }
    }
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=1000" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= display_meta_tags(default_meta_tags) %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-226705750-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-226705750-1');
    </script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>

    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/results/index.html.erb
<div class="mb-5 mt-5">
  <% @tweets.each do |tweet| %>
  <p><%= "#{tweet}" %></p>
<% end %>
  <%= button_to '戻る', root_path, method: :get, class: 'back-button' %>
</div>

app/views/results/show.html.erb
<% content_for(:title, '診断結果') %>
<section id="results" class="results section-bg">
  <div class="container">
    <div class="result-wrapper">
      <!-- 結果表示ページ -->

      <!-- 名前表示 -->
      <div class="result-name">
        <h1 class="result-name is-opacity" id="result-name"><%= @user.name %>さんの診断結果</h1>
      </div>

      <!-- こじらせレベル表示 -->
      <div class="kojirase-level-title">
        <h1 class="kojirase-level-title is-opacity" id="kojirase-level-title"><%= @kojirase_result.name %></h1>
      </div>


      <!-- グラフ表示 -->
        <%= render 'shared/kojirase_chart' %>

      <!-- こじらせメッセージ -->
      <div class="kojirase-message">
        <ul>
          <li class="kojirase-message is-opacity" id="kojirase-message"><%= @kojirase_result.description %></li>
          <li class="follower-message is-opacity" id="follower-message"><%= @follower_saying.message %></li>
          <li class="advice-message is-opacity" id="advice-message"><%= @kojirase_result.advice %></li>
        </ul>
      </div>

      <!-- 処方箋 -->
      <div class="prescription">
        <h1 class="prescription-label is-opacity" id="prescription-label">処方箋</h1>
          <%= render 'shared/youtube' %>
      </div>
    </div>
  </div>

  <div class="text-center back-btn">
    <%= button_to 'トップへ戻る', root_path, method: :get, class: 'btn btn-malformation shadow' %>
  </div>

  <div class='twitter-button'>
    <%= link_to "https://twitter.com/share?&url=https://kojirase-shindan.com/&text=【#{@user.name}】さんは【#{@kojirase_result.name}】です。&hashtags=こじらせ診断,婚活,メンヘラ,恋愛&lang=ja", title: 'Twitter', target: :_blank, rel: 'noopener noreferrer' do %>
      <i class="fab fa-twitter share-button"></i>
    <% end %>
  </div>
</section>

app/views/shared/_footer.html.erb
<footer class="text-muted py-3  w-100" id="footer">
    <div class="text-center">
      <div class="row">
        <div class="col">
          <%= link_to image_tag('logo1.png'), root_path, class:"logo-img" %>
        </div>
        <div class="col">
          <%= link_to 'お問い合せ', "https://docs.google.com/forms/d/e/1FAIpQLSeWG6MyzFwicUtaeYUGjXBBjaeKHF9nkgEUuXcRc66XmLaTIg/viewform?embedded=true", class: 'link-button'  %>
        </div>
        <div class="col">
          <%= link_to '利用規約', terms_path, class: 'link-button' %>
        </div>
        <div class="col">
          <%= link_to 'プライバシーポリシー', privacy_path, class: 'link-button' %>
        </div>
      </div>
      <div class="col-12">
        <div class="copyright">
          <p>Copyright © 2022 こじらせ診断</p>
        </div>
      </div>
    </div>
</footer>

app/views/shared/_kojirase_chart.html.erb
    <input type="hidden" id="follower" value="<%= @follower_point %>">
    <input type="hidden" id="apo" value="<%= @apo_point %>">
    <input type="hidden" id="numa" value="<%= @numa_point %>">
    <input type="hidden" id="spec" value="<%= @spec_point %>">
    <input type="hidden" id="desperate" value="<%= @desperate_point %>">

    <canvas id="kojiraseChart"></canvas>
    <script>
    var follower = document.getElementById('follower').value
    var apo = document.getElementById('apo').value
    var numa = document.getElementById('numa').value
    var spec = document.getElementById('spec').value
    var desperate = document.getElementById('desperate').value

    var ctx = document.getElementById("kojiraseChart");
    var kojiraseChart = new Chart(ctx, {
      //グラフの種類
      type: 'radar',
      //データの設定
      data: {
        //データ項目のラベル
        labels: [`有名度 ${follower}`, `アポ度 ${apo}`, `沼度 ${numa}`, `高望み度 ${spec}`, `生き遅れ度${desperate}`],
        //データセット
        datasets: [{
              //背景色
              backgroundColor: "rgba(185, 113, 233, 0.937)",
              pointBackgroundColor: "rgba(114, 5, 187, 0.937)",
              //結合点の枠線の色
              pointBorderColor: "rgba(114, 5, 187, 0.937)",
              borderColor: "rgba(114, 5, 187, 0.937)",
              borderWidth: 2,
              //グラフのデータ
              data: [follower, apo, numa, spec, desperate]
            }
          ]
      },
        options: {
        // レスポンシブ指定
        responsive: true,
        // タイトルについて
        legend: {
          display: false
        },
        scale: {
          // グリッド線の設定
          gridLines: {
            color: 'white',
            lineWidth: 5,
          },
          // 点ラベルの設定
          pointLabels: {
            fontSize: 28,
            fontColor: 'white',
          },
          ticks: {
            fontColor: 'black',
            display: false,
            min: 0,
            max: 5,
            stepSize: 5
          },
          angleLines: {
            display: true,
            color: "grey",
            lineWidth: 1.5
          }
        }
      }
    });
    </script>

app/views/shared/_youtube.html.erb
<h3 class="prescription-contents is-opacity" id="prescription-contents">
  <% if @kojirase_level == 1 %>
    こじらせる前に猫の動画を観て癒されましょう
  <% elsif @kojirase_level == 2 || @kojirase_level == 3 %>
    一旦可愛い猫の動画を観て心を落ち着けましょう
  <% elsif @kojirase_level == 4 || @kojirase_level == 5 %>
    重症なので猫の動画を観て癒されましょう
  <% end %>
</h3>
<div class="youtube-videos p-5">
  <% @cat_youtube_data.items.each do |item| %>
  <% snippet = item.snippet %>
    <div class="card-group">
      <div class="card">
        <%= content_tag 'iframe', nil, height: 300, src: "https://www.youtube.com/embed/#{item.id.video_id}", \
      frameborder: 0, gesture: 'media', allow: 'encrypted-media', allowfullscreen: true %>
        <div class="card-body">
          <div class="card-text">
            <h3><%= snippet.title %></h2>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/static_pages/privacy.html.erb
<% content_for(:title, 'プライバシーポリシー')%>
<section id="privacy" class="privacy section-bg">
  <div class="container">
    <div class="section-title">
      <h2>プライバシーポリシー</h2>
      <p>こじらせ診断運営者（以下「運営者」）は、運営するウェブサイト「こじらせ診断」において提供される全てのサービス（以下「本サービス」）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。</p>
    </div>

    <h3 class="privacy-title">第1条（個人情報）</h3>
      <div class="privacy-description">
        <p>個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。</p>
      </div>
    <h3 class="privacy-title">第2条（個人情報の収集方法）</h3>
      <div class="privacy-description">
        <p>運営者は，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,運営者の提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。</p>
      </div>
    <h3 class="privacy-title">第3条（個人情報を収集・利用する目的）</h3>
      <div class="privacy-description">
        <p>運営者が個人情報を収集・利用する目的は，以下のとおりです。</p>
        <ol>
          <li>本サービスの提供・運営のため</li>
          <li>ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）</li>
          <li>ユーザーが利用中のサービスの新機能，更新情報，キャンペーン等及び運営者が提供する他のサービスの案内のメールを送付するため</li>
          <li>メンテナンス，重要なお知らせなど必要に応じたご連絡のため</li>
          <li>利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため</li>
          <li>ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため</li>
          <li>有料サービスにおいて，ユーザーに利用料金を請求するため</li>
          <li>上記の利用目的に付随する目的</li>
        </ol>
      </div>
    <h3 class="privacy-title">第4条（利用目的の変更）</h3>
      <div class="privacy-description">
        <ol>
          <li>運営者は，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。</li>
          <li>利用目的の変更を行った場合には，変更後の目的について，運営者所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。</li>
        </ol>
      </div>
    <h3 class="privacy-title">第5条（個人情報の第三者提供）</h3>
      <div class="privacy-description">
        <ol>
          <li>運営者は，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。</li>
            <ol>
              <li>人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき</li>
              <li>公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき</li>
              <li>国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき</li>
              <li>予め次の事項を告知あるいは公表し，かつ運営者が個人情報保護委員会に届出をしたとき</li>
              <ol>
                <li>利用目的に第三者への提供を含むこと</li>
                <li>第三者に提供されるデータの項目</li>
                <li>第三者への提供の手段または方法</li>
                <li>本人の求めに応じて個人情報の第三者への提供を停止すること</li>
                <li>本人の求めを受け付ける方法</li>
              </ol>
            </ol>
          <li>前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。</li>
            <ol>
              <li>運営者が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</li>
              <li>合併その他の事由による事業の承継に伴って個人情報が提供される場合</li>
              <li>個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合</li>
            </ol>
        </ol>
      </div>
    <h3 class="privacy-title">第6条（個人情報の開示）</h3>
      <div class="privacy-description">
        <ol>
          <li>運営者は，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。なお，個人情報の開示に際しては，1件あたり1,000円の手数料を申し受けます。</li>
            <ol>
              <li>本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合</li>
              <li>運営者の業務の適正な実施に著しい支障を及ぼすおそれがある場合</li>
              <li>その他法令に違反することとなる場合</li>
            </ol>
          <li>前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。</li>
        </ol>
      </div>
    <h3 class="privacy-title">第7条（個人情報の訂正および削除）</h3>
      <div class="privacy-description">
        <ol>
          <li>ユーザーは，運営者の保有する自己の個人情報が誤った情報である場合には，運営者が定める手続きにより，運営者に対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。</li>
          <li>運営者は，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。</li>
          <li>運営者は，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。</li>
        </ol>
      </div>
    <h3 class="privacy-title">第8条（個人情報の利用停止等）</h3>
      <div class="privacy-description">
        <ol>
          <li>運営者は，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。</li>
          <li>前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。</li>
          <li>運営者は，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。</li>
          <li>前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。</li>
        </ol>
      </div>
    <h3 class="privacy-title">第9条（プライバシーポリシーの変更）</h3>
      <div class="privacy-description">
        <ol>
          <li>本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。</li>
          <li>運営者が別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。</li>
        </ol>
      </div>
  </div>
  <div class="text-center back-btn">
    <%= button_to 'トップへ戻る', root_path, method: :get, class: 'btn btn-malformation shadow' %>
  </div>
</section>

app/views/static_pages/top.html.erb
<section id="top" class="d-flex flex-column align-items-center justify-content-center">
  <%= image_tag 'logo' %>
</section>
<div class="container">
  <div class="sub-title">
    <h1>ツイッターのIDを入力するだけで</h1>
    <h1>あなたのこじらせ度を診断します！</h1>
  </div>

  <div class='top-image'>
    <%= image_tag 'top-girl', class: 'top-girl' %>
  </div>

  <div class="box-wrapper">
    <div class="box">
      <div class="img">
        <%= image_tag 'text1', size: '600x600' %>
      </div>
    </div>

    <div class="box">
      <div class="img">
        <%= image_tag 'text2', size: '600x600' %>
      </div>
    </div>

    <div class="box">
      <div class="img">
        <%= image_tag 'text3', size: '600x600' %>
      </div>
    </div>

    <div class="box">
      <div class="img">
        <%= image_tag 'text4', size: '600x600' %>
      </div>
    </div>
  </div>

  <div class="sub-title">
    <h1>どれかひとつ当てはまったあなたは</h1>
    <h1>実はこじらせているかも？</h1>
    <h1>いますぐ診断しましょう！</h1>
  </div>

  <div class="flash-message">
    <%= h(flash[:danger]) %>
  </div>

  <div id="analysis-button-wrapper">
    <%= form_with url: results_path, method: :get, local: true do |f| %>
      <div class="form-contents">
        <%= f.text_field :user, autofocus: true, class: 'form-control', placeholder: 'IDを入力', id: 'form-id' %>
      </div>
      <div class="form-contents">
        <%= f.submit '診断する', class: 'analysis-button', onclick:"clickAnalysisButton()", id: 'analysis-button', data: { disable_with: '診断中...' } %>
      </div>
    <% end %>
  </div>
</div>